services:
    frontend:
        build:
            context: ./coducate-frontend
            dockerfile: Dockerfile
        image: ghcr.io/madbeamer/coducate-frontend:latest
        ports:
            - "3000:3000"
        depends_on:
            - backend

    backend:
        build:
            context: ./coducate-backend
            dockerfile: Dockerfile
        image: ghcr.io/madbeamer/coducate-backend:latest
        ports:
            - "1234:1234"
